version: '3.8'

services:
  whatsapp-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=whatsapp_bot
      - PORT=8080
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - bot-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - bot-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - bot-network

volumes:
  mongo-data:

networks:
  bot-network:
    driver: bridge